modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_bug_tracker}"
clientSideOnly = ${forge_client_side_only}
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "${forge_update_url}"
displayURL = "${mod_homepage}"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author_name} <${mod_author_email}>"
description = '''${mod_description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
