# === Project Properties
mod_name=Expanded Gamerules
mod_id=expanded_gamerules
mod_group=com.glektarssza.expanded_gamerules
mod_version=0.1.0
mod_author_name="G'lek Tarssza"
mod_author_email=glek@glektarssza.com
mod_description="A Minecraft mod that adds a collection of new gamerules to let you play the game the way YOU want to play it!"
mod_license="Copyright (c) 2026 to present G'lek Tarssza under a modified MIT License. See LICENSE.md for the full license."
mod_credits="G'lek Tarssza for the mod implementation."
mod_homepage=https://git.disroot.org/glektarssza-mc-modding/expanded-gamerules
mod_source=https://git.disroot.org/glektarssza-mc-modding/expanded-gamerules
mod_bug_tracker=https://git.disroot.org/glektarssza-mc-modding/expanded-gamerules/issues
mixins_package=com.glektarssza.expanded_gamerules.mixins

# === Common Project Properties ===
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.3)
java_version=21
# This version is used in the "common" project, hence why it's up here
neoform_version=1.21.1-20240808.144430
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# === Forge Project Settings ===
forge_version=52.1.14
forge_version_range=[52,53)
forge_loader_version_range=[1,)
forge_client_side_only=false
forge_update_url=https://git.disroot.org/glektarssza-mc-modding/expanded-gamerules/raw/branch/main/updates.json

# === NeoForge Project Settings ===
neoforge_version=21.1.225
neoforge_version_range=[21,22)
neoforge_loader_version_range=[1,)
neoforge_update_url=https://git.disroot.org/glektarssza-mc-modding/expanded-gamerules/raw/branch/main/updates.json

# === Fabric Project Settings ===
fabric_version=0.116.10+1.21.1
fabric_loader_version=0.19.1
fabric_entrypoint=com.glektarssza.expanded_gamerules.ExpandedGamerules

# === Gradle Settings ===
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.welcome=never
org.gradle.workers.max=4
