# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  workflow_call:
    secrets:
      github-token:
        description: |
          The token to use when making authenticated calls to the GitHub API.
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          distribution: temurin
          java-package: jdk
          java-version: 21
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - id: build
        name: Build
        run: ./gradlew build
      - id: upload-forge-artifacts
        name: Upload Forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-forge
          path: forge/build/libs/
          compression-level: 0
          if-no-files-found: error
      - id: upload-fabric-artifacts
        name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-fabric
          path: fabric/build/libs/
          compression-level: 0
          if-no-files-found: error
      - id: upload-neoforge-artifacts
        name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-neoforge
          path: neoforge/build/libs/
          compression-level: 0
          if-no-files-found: error
